### PR TITLE
Fix for firefox

### PR DESCRIPTION
**Pull request by mkg20001**
This fixes a bug with the options page on firefox.

Due to ff 57+ web extension support you can just publish this addon for firefox as-is now.

### CODE REVIEW

**Comment by SeinopSys** [comment]
I didn't publish to Firefox in the first place because the extension did not seem to send any visible notifications, it would just play the sound.

**Comment by mkg20001** [comment]
Is there any way to create fake-notifications? Because I have yet to get a notification to test that...

**Comment by SeinopSys** [comment]
You could send a message to yourself and mark it as unread.

**Comment by mkg20001** [comment]
I've found something:
```
[firefox/index.js][debug] Firefox stdout: Extension error: Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create. moz-extension://973f7ef6-d722-4b62-b66f-9f35ce105e95/js/background.js 374
[[Exception stack
setBadgeText/<@moz-extension://973f7ef6-d722-4b62-b66f-9f35ce105e95/js/background.js:374:6
Current stack
applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:303:133
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:470:13
]]
[firefox/index.js][debug] Firefox stdout: Extension error: Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create. moz-extension://973f7ef6-d722-4b62-b66f-9f35ce105e95/js/background.js 374
[[Exception stack
setBadgeText/<@moz-extension://973f7ef6-d722-4b62-b66f-9f35ce105e95/js/background.js:374:6
Current stack
applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:303:133
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:470:13
]]
```

Fixed it by disabling the buttons on firefox. This should be removed once they support it.

**Comment by SeinopSys** [comment]
That kinda sucks because the buttons are what allow you to go to the notifications or messages page from the notification directly.

**Comment by mkg20001** [comment]
This seems to be tracked upstream here: https://bugzilla.mozilla.org/show_bug.cgi?id=1190681
`onClicked` could still be used to open the page. But that makes no sense for two buttons...

**Comment by SeinopSys** [comment]
Yeah. I'm not entirely sure it's worth submitting the extension as Firefox compatible until the button situation is sorted out.

**Comment by mkg20001** [comment]
_Still better than nothing._
Added some code to make it only disable buttons if they're still unsupported.

**Comment by mkg20001** [comment]
Looks like bugzilla has a voting system: https://bugzilla.mozilla.org/page.cgi?id=voting/user.html&bug_id=1190681#vote_1190681

**Comment by SeinopSys** [comment]
Voted on the issue and made some style adjustments. I'll test this myself as well later.

**Pull request merged**
